name: Ruff Formatting
on: [pull_request]
jobs:
  ruff:
    if: ${{ github.actor != 'dependabot[bot]' }} # Do not run on commits created by dependabot
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files.
      contents: write # Allows reading and writing repository contents (e.g., commits)
      pull-requests: write # Allows reading and writing pull requests
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: astral-sh/ruff-action@v3
        with:
          src: "./src/teloclip ./tests"
          args: "format"
      - uses: astral-sh/ruff-action@v3
        with:
          src: "./src/teloclip ./tests"
          args: "check --fix"
      - uses: isort/isort-action@v1
        with:
          configuration: "--settings-path=./pyproject.toml"
          paths: "./src/teloclip ./tests"
      - uses: stefanzweifel/git-auto-commit-action@v7
        id: auto-commit-action
        with:
          commit_message: "Style fixes by Ruff"
